### ISSUE TITLE
Incorrect min date for S1GRD

### ISSUE THREAD

**Issue by Ardweaden** [sentinel-hub/sentinelhub-js#199]
https://github.com/sentinel-hub/sentinelhub-js/blob/9ac2749a6ab55345c5cc3f4415efefc8b49cd176/src/layer/dataset.ts#L26

There seems to be data before that date.

**Comment by zcernigoj** [comment]
According to [SH Docs](https://docs.sentinel-hub.com/api/latest/data/sentinel-1-grd/#endpoint-locations) the data is available from October 2014 onward. So, probably true :+1:
