### ISSUE TITLE
Change token endpoint to the new endpoint

### ISSUE THREAD

**Issue by Ardweaden** [sentinel-hub/sentinelhub-js#256]
https://github.com/sentinel-hub/sentinelhub-js/blob/4a38647785412e7b49ba007248441a496c12ec5b/src/auth.ts#L20

Change to `https://services.sentinel-hub.com/auth/realms/main/protocol/openid-connect/token`.

Check if this is used anywhere else.

@dthiex

**Comment by dthiex** [comment]
Someone will check, thanks!
